

export const Actions = {
    SELECT_TICKET: 'SELECT_TICKET',
    ADD_TICKET: 'ADD_TICKET',
    SHOW_ADD_TICKET: 'SHOW_ADD_TICKET',
    HIDE_ADD_TICKET: 'HIDE_ADD_TICKET',
    ADD_LANE: 'ADD_LANE',
    UNSELECT_TICKET: 'UNSELECT_TICKET',
    MOVE_TICKET: 'MOVE_TICKET'
}